### ISSUE TITLE
Add a _renderView method on the Lobby that redirects to a view based on the lobbyStatus

### ISSUE THREAD

**Issue by PaulMacinic** [e-spres-oh/qwizard#20]

**Comment by horiaradu** [comment]
have a single URL for all these things => simple error handling:

if lobby is **pending**
* if no player, take to SelectHat
* if player, take to lobby

if lobby is **started**
* if no player => no go
* if player => play screen (can be question / inbetween)

if lobby is **ended**
* => hall of fame
